# Flyberry Brand Book Evaluation
# Evaluates the quality of LLM-generated brand strategy for Flyberry

description: "Flyberry Brand Book Quality Evaluation"

prompts:
  - file:///Users/kalpeshjaju/Library/CloudStorage/GoogleDrive-kalpesh@whatgoesaroundcomesaround.in/My Drive/claude_kalpesh/brand-design-agent/outputs/flyberry/COMPLETE-BRAND-BOOK.md

providers:
  - id: anthropic:messages:claude-sonnet-4-20250514
    config:
      temperature: 0.2
      max_tokens: 1000

tests:
  - description: "Market Research Quality"
    assert:
      - type: llm-rubric
        value: |
          Evaluate the Market Research section for Flyberry:

          1. Industry Trends: Are the 7 trends specific, relevant, and well-researched for healthy snacks in India?
          2. Competitive Analysis: Does it cover 3+ competitors with meaningful strengths/weaknesses/differentiation?
          3. Customer Insights: Are personas realistic and actionable?
          4. Data Quality: Does research feel grounded or generic?
          5. Strategic Value: Are insights actionable for decision-making?

          Score 0-10 (Pass if >= 7)
          - 0-3: Generic/weak research
          - 4-6: Decent but lacks depth
          - 7-8: Strong, actionable insights
          - 9-10: Exceptional depth and specificity
        provider: anthropic:messages:claude-sonnet-4-20250514

  - description: "Brand Strategy Completeness"
    assert:
      - type: llm-rubric
        value: |
          Evaluate the Brand Strategy section:

          1. Foundation: Does it include clear Purpose, Vision, Mission, Values?
          2. Positioning: Is the positioning statement specific and differentiated?
          3. Personality: Is brand personality well-defined with clear traits?
          4. Messaging: Are key messages, taglines, and elevator pitches compelling?
          5. Completeness: Does it feel like a complete brand strategy?

          Score 0-10 (Pass if >= 7)
        provider: anthropic:messages:claude-sonnet-4-20250514

  - description: "Strategic Differentiation"
    assert:
      - type: llm-rubric
        value: |
          Evaluate how well the brand strategy differentiates Flyberry:

          1. Unique Value: Does Flyberry have a clear, ownable position vs competitors?
          2. Competitive Edge: Are differentiation points credible and meaningful?
          3. White Space: Does it identify unoccupied market territories?
          4. Authenticity: Does the strategy align with Flyberry's actual business?
          5. Defensibility: Can competitors easily copy this positioning?

          Score 0-10 (Pass if >= 7)
        provider: anthropic:messages:claude-sonnet-4-20250514

  - description: "Actionability & Implementation"
    assert:
      - type: llm-rubric
        value: |
          Evaluate how actionable the strategy is:

          1. Clarity: Can someone execute this without further clarification?
          2. Prioritization: Are next steps clear and prioritized?
          3. Tactical Direction: Does it bridge strategy to execution?
          4. Measurability: Can success be tracked?
          5. Realism: Are recommendations feasible for a growing brand?

          Score 0-10 (Pass if >= 7)
        provider: anthropic:messages:claude-sonnet-4-20250514

  - description: "Content Quality & Professionalism"
    assert:
      - type: javascript
        value: |
          // Check basic quality markers
          const hasStructure = /#+.*/.test(output);
          const hasCompetitors = /Competitor|Happilo|Farmley|Nutty/.test(output);
          const hasTrends = /Trend|CAGR|Growth/.test(output);
          const hasStrategy = /Purpose|Vision|Mission|Values/.test(output);
          const reasonableLength = output.length > 10000;

          const score = [hasStructure, hasCompetitors, hasTrends, hasStrategy, reasonableLength]
            .filter(Boolean).length / 5;

          return {
            pass: score >= 0.8,
            score: score,
            reason: `Quality markers: ${Math.round(score * 100)}% (Structure: ${hasStructure}, Competitors: ${hasCompetitors}, Trends: ${hasTrends}, Strategy: ${hasStrategy}, Length: ${reasonableLength})`
          };

      - type: llm-rubric
        value: |
          Evaluate the overall quality and professionalism:

          1. Writing Quality: Is it clear, professional, and error-free?
          2. Structure: Is the document well-organized and easy to navigate?
          3. Depth: Does it go beyond surface-level insights?
          4. Consistency: Is the brand voice/tone consistent throughout?
          5. Polish: Does it feel like a deliverable from a professional agency?

          Score 0-10 (Pass if >= 7)
        provider: anthropic:messages:claude-sonnet-4-20250514

  - description: "India Market Specificity"
    assert:
      - type: llm-rubric
        value: |
          Evaluate how well the strategy addresses the Indian market:

          1. Cultural Relevance: Does it understand Indian consumer behavior?
          2. Local Context: Are insights specific to India (not generic global)?
          3. Market Nuances: Does it address Indian health food market dynamics?
          4. Competitive Context: Are Indian competitors accurately analyzed?
          5. Localization: Is language/framing appropriate for Indian audience?

          Score 0-10 (Pass if >= 7)
        provider: anthropic:messages:claude-sonnet-4-20250514

defaultTest:
  options:
    threshold: 0.7  # 70% passing score

outputPath: ./outputs/flyberry-evaluation-results.json
